aplikacja_raportowanie/urls.py
from django.urls import path
#from . import views
from aplikacja_raportowanie import views
from django.conf.urls import handler404
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


app_name = 'raportowanie'

urlpatterns = [
	path('', views.users_index, name="users_index"),
	path('list/', views.index, name = 'index'),
	path('list/quater/', views.index_quater, name='quater'),
	path('list/closed', views.index_closed, name='index_closed'),
	path('closed/', views.users_index_closed, name='users_index_closed'),
	path('long_terms/', views.long_index, name="long_terms"),
	path('list/usuniete/', views.index_deleted, name = "deleted_posts_index"),
	path('post/new/', views.post_new, name = 'post_new'),
	path('post/<int:post_id>/',  views.post_filled, name="post_filled"),
	path('post/<int:post_id>/edit/', views.post_edit, name="post_edit"),
	path('post/<int:post_id>/history', views.post_history, name="post_history"),
	path('post/<int:post_id>/deleted', views.delete_post, name="post_delete"),
	path('post/<int:post_id>/comment_delete/<int:comment_id>', views.delete_comment, name="comment_delete"),
	path('author_changing/<int:post_id>/', views.author_post_change, name = "author_post_change"),
	path('post/<int:post_id>/comment_history/<int:comment_id>/', views.comment_history, name = "comment_history"),
	path('post/<int:post_id>/comment_edit/<int:comment_id>', views.comment_edit, name="comment_edit"),
	path('login/', views.login_view, name="login"),
	path('logout/', views.logout_view, name="logout_"),

]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'aplikacja_raportowanie.views.handler404'

projekt/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('aplikacja_raportowanie.urls')),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aplikacja_raportowanie/forms.py
from django import forms
import datetime
from .models import Post, Comment, STATUS_CHOICES

class PostForm(forms.ModelForm):
    title = forms.CharField(label="Tytuł*")
    text = forms.CharField(label="Treść*", widget=forms.Textarea)
    QM_id = forms.DecimalField(max_digits=20, decimal_places=0, required=False)
    status = forms.ChoiceField(choices=STATUS_CHOICES, label="Status*")
    file = forms.FileField(label="Załącznik", help_text='max. 20MB', required=False)
    tictet_number = forms.CharField(label="TW/SWING ticket", required=False)
    long_term = forms.BooleanField(label = "Problem dugotrwaly", required=False)
    class Meta:
        model = Post
        fields = ('title',"text","long_term", "status", "QM_id", "tictet_number", "file")

class CommentForm(forms.ModelForm):
    text = forms.CharField(label = "Treść*", widget=forms.Textarea)
    status = forms.ChoiceField(choices=STATUS_CHOICES, label="Status*")
    file = forms.FileField(label = "Załącznik", help_text='max. 20MB', required=False)
    class Meta:
        model = Comment
        fields = ('text', 'status', 'file')

aplikacja_raportowanie/views.py
from aplikacja_raportowanie.functions_to_view import *
from aplikacja_raportowanie.view_class import *


#Funkcja wypełniająca stronę początkową uzytkownika
@login_required(login_url="/login/")
def users_index(request):
	users_index = View_type(request, which_index_view(request, "user_index"), which_index_view(request, "posts_to_do"), f"Twoje aktywne zgłoszenia ({logged_user(request)})")
	return users_index.render_view(request)

#Funkcja wypełniająca stronę początkową grupy
@login_required(login_url="/login/")
def index(request):
	index = View_type(request, which_index_view(request, "index"), which_index_view(request, "posts_to_do"), "Aktywne zgłoszenia grupy")
	return index.render_view(request)

#Wyświetl tylko zamknięte zgłoszenia użytkownika
@login_required(login_url="/login/")
def users_index_closed(request):
	index = View_type(request, which_index_view(request, "users_index_closed"),False, f"Twoje zamknięte zgłoszenia ({logged_user(request)})")
	return index.render_view(request)

#Wyświetl tylko zamknięte zgłoszenia grupy
@login_required(login_url="/login/")
def index_closed(request):
	index = View_type(request, which_index_view(request, "index_closed"),False, "Wszystkie zamknięte zgłoszenia")
	return index.render_view(request)

#Wyświetla listę usuniętych zgłoszeń
@login_required(login_url="/login/")
def index_deleted(request):
	index = View_type(request, which_index_view(request, "index_deleted"),False, "Wszystkie usunięte zgłoszenia")
	return index.render_view(request)

@login_required(login_url="/login/")
def long_index(request):
	index = View_type(request, which_index_view(request, "long_index"), False, "Zgłoszenia dlugoterminowe")
	return index.render_view(request)

#Wyświetla widok postów filtrowanych po kwartale
@login_required(login_url="/login/")
def index_quater(request):
	if request.method == "POST":
		start_date = request.POST['pic-a-date-start-']
		stop_date = request.POST['pic-a-date-stop-']
		date = str(start_date) + " 00:00", str(stop_date) + " 23:59"
		status = request.POST.getlist('status-pick-a-quater')
		author = str(request.POST['author-pick-a-quater'])
		what_ = str(request.POST['what-state-pick-a-quater'])
		date_type = str(request.POST['date'])
		print(date_type)
		posts = which_quater(request, date, status, author, what_, date_type)
		view_type = str(quater_string(date)) + ", " + str(status_name_filter(str(status))) + ", " + author + ", " + what_.replace('-', "/", 1).replace('_', ' ')
		index = View_type(request, posts,False, view_type)
		return index.render_view(request)
	else:
		return redirect('raportowanie:index')

#Wyświetla historię edycji posta
@login_required(login_url="/login/")
def post_history(request, post_id):
	try:
		post_history = Post.objects.get(id=post_id)
	except Post.DoesNotExist:
		return handler404(request,None)
	content = {
		"post_history": post_history.history.all(),
		"post": post_history
	}
	return render(request, 'aplikacja_raportowanie/post_history.html', content)


#Wyświetla historię edycji komentarza
@login_required(login_url="/login/")
def comment_history(request, post_id, comment_id):
	try:
		comment_history = Comment.objects.get(id=comment_id)
	except Comment.DoesNotExist:
		return handler404(request,None)

	content = {
		"comment_history": comment_history.history.all(),
		"post": Post.objects.get(id=post_id)
	}
	return render(request, 'aplikacja_raportowanie/comment_history.html', content)



#Usuwa posta z głównej listy i przenosi go na listę usunięte
@login_required(login_url="/login/")
def delete_post(request,post_id):
	try:
		post = Post.objects.get(id=post_id)
	except Post.DoesNotExist:
		return handler404(request,None)
	if post.is_deleted == True:
		pass
	else:
		post.is_deleted = True
		post.modify_date = timezone.now()
		post.status = "zamknięte"
		post.change = "Usunięcie"
		post.save()
		comment = Comment(text="USUWAM", publish_date = timezone.now(), status="USUWANIE zgłoszenia", author=logged_user(request))
		comment.save()
		comment.post_id.add(post.id)
	return redirect('raportowanie:post_filled', post_id=post.id)

@login_required(login_url="/login/")
def delete_comment(request, post_id, comment_id):
	try:
		post = Post.objects.get(id=post_id)
	except Post.DoesNotExist:
		return handler404(request,None)
	if request.method == "POST":
		try:
			comment = Comment.objects.get(id=comment_id)
		except Comment.DoesNotExist:
			return handler404(request,None)

		if comment.is_deleted == True:
			pass
		else:
			comment.is_deleted = True
			comment.modify_author = logged_user(request)
			comment.save()
			post.change = f"Usunięto koemntarz {comment_id}"
			post.save()
	return redirect('raportowanie:post_filled', post_id=post.id)


#Funkcja wypelniająca stronę z istniejcym zgłoszeniem i daje możliwość komentowania
@login_required(login_url="/login/")
def post_filled(request, post_id):
	try:
		post = Post.objects.get(id=post_id)
	except Post.DoesNotExist:
		return handler404(request,None)
	if request.method == "POST":
		form = CommentForm(request.POST, request.FILES)
		if form.is_valid():
			comment = form.save(commit=False)
			comment.publish(request)
			post_first_status = post.status
			post.status = comment.status
			if post.status == "do podjęcia":
				post.author = None
			else:
				post.author = request.user
			post.change = status_change_field(post_first_status, post.status, "Zamknięcie", "Ponowne otwarcie", "Dodanie komentarza", "Ponowne otwarcie, do podjęcia", "Podjęcie zgłoszenia")
			post.modify_date = timezone.now()
			post.save()
			comment.post_id.add(str(post.id))
	else:
		form = CommentForm()

	comments = Comment.objects.filter(is_deleted = False, post_id=post.id).order_by("-publish_date")

	content = {
		"login_user": logged_user(request),
		"post" : post,
		"comments": comments,
		"status_color": status_colors(post),
		"form": form,
		"users": list_of_users(),
		 }
	return render(request, 'aplikacja_raportowanie/post_filled.html', content)

#Funkcja do wyswietlania strony pozwalającej tworzyć nowe zgłoszenie
@login_required(login_url="/login/")
def post_new(request):
	if request.method == "POST":
		form = PostForm(request.POST, request.FILES)
		if form.is_valid():
			post = form.save(commit=False)
			start_date = request.POST['post-start-date']
			start_time = request.POST['post-start-time']
			post.publish(request, start_date, start_time, post.status)
			return redirect('raportowanie:post_filled', post_id=post.id)
	else:
		form = PostForm()
	content = {
		"login_user": logged_user(request),
		"view_type_hyperlink": "../../",
		'form': form,
		"date": str(timezone.now().date()),
		"time": str(timezone.now().time())[0:5],
		"view_type": "Nowe zgłoszenie",
		"name_of_form": "Formularz tworzenia zgloszenia"

	}
	return render(request, 'aplikacja_raportowanie/post_new.html', content)

#Funkcja do edycji obenego zgłoszenia
@login_required(login_url="/login/")
def post_edit(request, post_id):
	try:
		post = Post.objects.get(id=post_id)
	except Post.DoesNotExist:
		return handler404(request,None)
	post_first_status = post.status
	start_date_split_list = str(post.start_date).split(" ") #dzielimy start_date na date i czas
	date_ = start_date_split_list[0]  #uzyskujemy samą date, a 'date' w pliku html to value inuta date
	time = start_date_split_list[1][0:5] #uzyskujemy samą godzine, a 'time' w pliku html to value inuta time
	if request.method == "POST":
		form = PostForm(request.POST,request.FILES, instance=post)
		if form.is_valid():
			post = form.save(commit=False)
			start_date = str(request.POST["post-start-date"]) + ' ' + 	str(request.POST["post-start-time"])
			change = status_change_field(post_first_status, post.status, "Edycja, zamknięcie", "Edycja, ponowne otwarcie", "Edycja", "Otwarcie, do podjęcia", "Podjęcie zgłoszenia")
			post_new_status = f"Edytuje zgłoszenie, {post.status}"
			comment = Comment(text="Edytuje zgłoszenie", publish_date = timezone.now(), status=post_new_status, author=logged_user(request))
			comment.save()
			comment.post_id.add(post.id)
			post.edit(start_date, change, post.status)
			return redirect('raportowanie:post_filled', post_id=post.id)
	else:
		form = PostForm(instance=post)
	content = {
		"login_user": logged_user(request),
		"view_type_hyperlink": "../" + str(post.id),
		"view_type": "Modyfikacja zgloszenia nr. " + str(post.id),
		"back_to_post": "Zgłoszenie nr. "+ str(post.id),
		'form': form,
		"date": date_,
		"time": time,
		"post_id": post_id,
		"name_of_form": "Fromularz edycji zgłoszenia " + str(post.id)
	}
	return render(request, 'aplikacja_raportowanie/post_new.html', content)



#Funkcja pozwalająca zmianę właściciela posta
@login_required(login_url="/login/")
def author_post_change(request, post_id):
	if request.method == "POST":
		new_post_author = request.POST['new-author-of-post']

		try:
			post = Post.objects.get(id=post_id)
		except Post.DoesNotExist:
			return handler404(request,None)
		old_author = post.author

		if old_author:
			comment_status = "ZMIANA WŁAŚCICIELA Z @" + str(old_author) + " NA @"  + str(new_post_author)
			change = "Zmiana właściciela"
		else:
			comment_status = "Ustawiono właściciela na @" + str(new_post_author)
			change = "Ustawienie właściciela"

		post.author_change(new_post_author, change)
		comment = Comment(text=str(request.POST['comment-text-after-author-edit']), publish_date=timezone.now(), status=comment_status, author=logged_user(request))
		comment.save()
		comment.post_id.add(post.id)
		return redirect('raportowanie:post_filled', post_id=post.id)
	else:
		return redirect('raportowanie:post_filled', post_id)




#Funkcja pozwalająca edycję komentarza
@login_required(login_url="/login/")
def comment_edit(request, post_id, comment_id):
	try:
		post = Post.objects.get(id=post_id)
	except Post.DoesNotExist:
		return handler404(request,None)
	comment = Comment.objects.get(id = comment_id)
	if request.method == "POST":
		form = CommentForm(request.POST, request.FILES, instance=comment)
		if form.is_valid():

aplikacja_raportowanie/templates/aplikacja_raportowanie/base_filled_page.html
{% extends 'aplikacja_raportowanie/base_layout.html' %}

{% block content %}


  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-dark sidebar sidebar-dark accordion margin-top100" id="accordionSidebar">

    </ul>



    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-dark sidebar sidebar-dark accordion fixed-top margin-top100" id="accordionSidebar">

      <!-- Sidebar - Brand -->
     <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
       <div class="sidebar-brand-icon rotate-n-15">
         <i class="fas fa-laugh-wink"></i>
       </div>
       <div class="sidebar-brand-text mx-3">Cześć! <sup></sup></div>
     </a>
     <!-- Divider -->
      <hr class="sidebar-divider my-0">
      <!-- Heading -->
      <div class="sidebar-heading">
        Menu
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-list"></i>
          <span>Listy</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Wybór listy zdarzeń</h6>
            <a class="collapse-item" href="{% url 'raportowanie:users_index' %}">Twoja lista zdarzeń</a>
            <a class="collapse-item" href="{% url 'raportowanie:index' %}">Lista zdarzeń grupy</a>
            <a class="collapse-item" href="{% url 'raportowanie:index_closed' %}">Zamknięte</a>
            <a class="collapse-item" href="{% url 'raportowanie:users_index_closed' %}">Twoje zamknięte</a>
            <a class="collapse-item" href="{% url 'raportowanie:long_terms' %}">Zgłoszenia dlugoterminowe</a>
          </div>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'raportowanie:post_new' %}">
          <i class="fas fa-fw fa-plus"></i>
          <span>NOWE zgłoszenie</span></a>
      </li>
    </ul>

    <div id="content-wrapper" class = "margin-auto">
      <div class="margin-left margin-top50 backgroud-dark">

      <div class="container-fluid">

        <!-- Breadcrumbs-->
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'raportowanie:index' %}">Lista zdarzeń</a>
          </li>
          <li class="breadcrumb-item">
            <a>Zgloszenie nr. {{post.id}}</a><!-- TU WPISUJEMY ADRES STRONY STARTOWEJ -->
          </li>
        </ol>



        <!--  CONTENT -->
        {% block post_filled %}
        {% endblock %}
        </div>


        <!-- ModalToEditAuthorInPostWithACommant -->
        <div class="modal fade" id="ChangeAuthorWithACommantModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content backgroud-dark">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Zmiana właściciela</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form action = "{% url 'raportowanie:author_post_change' post_id=post.id %}" method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="recipient-name" class="col-form-label">Nowy właściciel:</label>
                    <select value={{post.author}} name="new-author-of-post">
                      {% for author in users %}
                        <option value="{{author}}">{{author}}</option>
                      {% endfor %}
                    </select>
                  </div>
                  <div class="form-group">
                    <label for="message-text" class="col-form-label">Komentarz:</label>
                    <textarea class="form-control" name="comment-text-after-author-edit" required></textarea>
                  </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-dark" data-dismiss="modal" rel-data-toggle="tooltip" data-placement="bottom"
					title="Anuluj"><i class="fas fa-ban"></i></button>
                <button type="submit" class="btn btn-primary" rel-data-toggle="tooltip" data-placement="bottom"
					title="Potwierdź"><i class="fas fa-check"></i></button>
              </form>
              </div>
            </div>
          </div>
        </div>


<script>
  $('#ChangeAuthorWithACommantModal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget)
  var recipient = button.data('whatever')
  var modal = $(this)
  modal.find('.modal-title').text('New message to ' + recipient)
  modal.find('.modal-body input').val(recipient)
});
</script>



<!-- DeletePost modal -->
<div class="modal fade" id="DeletePostModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <form method="post" action="{% url 'raportowanie:post_delete' post_id=post.id %}">
        {% csrf_token %}
        <div class="modal-dialog" role="document">
            <div class="modal-content backgroud-dark">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">USUWANIE - Jesteś pewien?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">USUWASZ zdarzenie! Jest to operacja nieodwracalna (chyba że zapłacisz 5 dych adminowi)! Jesteś pewien swojego działania?</div>
                <div class="modal-footer">
                    <button class="btn btn-dark" type="button" data-dismiss="modal" rel-data-toggle="tooltip" data-placement="bottom"
					title="Anuluj"><i class="fas fa-ban"></i></button>
                    <button class="btn btn-danger" type="submit" rel-data-toggle="tooltip" data-placement="bottom"
					title="USUŃ"><i class="fas fa-trash" ></i></button>
                </div>
            </div>
        </div>
    </form>
</div>


<!-- DeletePost modal -->
<script>
  $(".confirm").confirm();
</script>


        <!-- /.container-fluid -->
      </div>
      <!-- /.content-wrapper -->
    </div>
    <!-- /#wrapper -->
  </div>

{% endblock %}

aplikacja_raportowanie/templates/aplikacja_raportowanie/comment_edit.html
{% extends 'aplikacja_raportowanie/base_new_page.html' %}

{% block hyperlink_type %}
<li class="breadcrumb-item">
  <a href="{% url 'raportowanie:index' %}">Lista zdarzeń</a>
</li>
<li class="breadcrumb-item">
  <a href="{% url 'raportowanie:post_filled' post.id %}">Zgloszenie nr. {{post.id}}</a>
</li>
<li class="breadcrumb-item">
  <a>Edycja komentarza</a>
</li>
{% endblock %}


{% block post_new_form %}
<!-- Page Content -->
<h1>Edycja komentarza</h1>
<hr>
<form method="POST" class="post-form" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
    <button type="button" class="btn btn-dark" data-toggle="modal" data-target="#CancellModal" data-whatever="cancell-change" rel-data-toggle="tooltip" data-placement="bottom"
					title="Anuluj"><i class="fas fa-ban"></i></button>
    <button class="btn btn-primary" type="submit" rel-data-toggle="tooltip" data-placement="bottom"
					title="Potwierdź"><i class="fas fa-check"></i></button>
</form>



{% endblock %}}


{% block go_back_to_post %} <form method="post" action=" {% url 'raportowanie:post_filled' post.id %} "> {% endblock %}

aplikacja_raportowanie/templates/aplikacja_raportowanie/post_filled.html
{% extends 'aplikacja_raportowanie/base_filled_page.html' %}

{% block post_filled %}
<!-- Page Content -->
    <form method="post">
     {% csrf_token %}
            <div class="d-flex mb-3 ">
                 <div class="ml-auto p-2">
                   <a type="button" class="btn btn-dark"  href="{% url 'raportowanie:post_edit' post_id=post.id %}" rel-data-toggle="tooltip" data-placement="bottom"
						title="Edycja"><i class="fas fa-edit"></i>
                         <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ChangeAuthorWithACommantModal" data-whatever="author-change" rel-data-toggle="tooltip" data-placement="bottom"
						title="Zmień właściciela"><i class="fas fa-users"></i></button>
                        <span class="glyphicon glyphicon-pencil"></span>
                    <a type="button" class="btn btn-warning"  href="{% url 'raportowanie:post_history' post_id=post.id %}" rel-data-toggle="tooltip" data-placement="bottom"
						title="Historia"><i class="fas fa-history"></i>
                        <span class="glyphicon glyphicon-pencil"></span>
                    <a type="button" class="btn btn-danger" data-toggle="modal" data-target="#DeletePostModal" data-whatever="delete-change" rel-data-toggle="tooltip" data-placement="bottom"
					title="Usun"><i class="fas fa-trash"></i></a>
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                </div>
            </div>
            <div class="p-2 ">
                <h6>Tytuł</h6>
                <h1>{{post.title}}</h1>
            </div>
            <h6>Treść zgłoszenia:</h6>
            <h4 class="post-text">{{post.text}}</h4><br>
            <style>
              .post-text{
                color: green
              }
              </style>
              <div class="d-flex bd-highlight mb-3">
                <div class="p-2 bd-highlight">
                  <h6>Właściciel</h6>
                  <h5>{{post.get_author}}</h5></div>
                <div class="p-2 bd-highlight">
                  <h6>Data startu problemu:</h6>
                  <h5>{{post.start_date | date:"Y-m-d H:i"}}</h5></div>
                <div class="p-2 bd-highlight">
                  <h6>Data publikacji:</h6>
                  <h5 align="right">{{post.publish_date | date:"Y-m-d H:i"}}</h5></div>
              <div class="p-2 bd-highlight">
                <h6>Status:</h6>
                <h5 class="status-info-color">{{post.status}}</h5></div>
              <div class="p-2 bd-highlight">
                <h6>QM id</h6>
                <h5><span class="{{post.get_QM_id_icon}}"></span> {{post.get_Qm_id}}</h5></div>
              <div class="p-2 bd-highlight">
                <h6>TW/SWING ticket</h6>
                <h5><span class="{{post.get_ticket_number_icon}}"></span> {{ post.get_ticket_number }}</h5></div>

              <div class="p-2 bd-highlight">
                <h6>Zalącznik:</h6>
                <a href="{{ post.get_absolute_file_url }}"><span class="{{post.if_post_have_file_icon}}" rel-data-toggle="tooltip" data-placement="bottom"
        title="{{post.file.name}}" > {{ post.if_there_is_a_file_return_text }}</a></div>
              </div>

    </form>
<div class="d-flex mb-3">
    <div class="p-2 ">


      </div>
  </div>


<!-- COMMENT BOX -->
<div class="row bootstrap snippets">
    <!-- <div class="col-md-6 col-md-offset-2 col-sm-12"> -->
    <div class="col-md-10 col-md-offset-2 col-sm-12">
        <div class="comment-wrapper">
            <h5>
                Skomentuj problem
            </h5>
                <form method="POST" class="comment-form" enctype="multipart/form-data">
                     {% csrf_token %}
                    <div>
                        {{ form.as_p }}
                    </div>
                    <div align="center">
                        <button class="btn btn-primary" type="submit" rel-data-toggle="tooltip" data-placement="bottom"
							title="Zatwierdź">
                            <i class="fas fa-check"></i>
                        </button>
                    </div>
                </form>
                    <hr>
            <ul class="media-list">
                {% for comment in comments %}
                <li class="media">
                    <a href="#" class="pull-left">
                        <img src="https://bootdey.com/img/Content/user_1.jpg" alt="" class="img-circle">
                    </a>
                    <div class="media-body">
                        <span class="text-muted pull-right">
                            <small class="text-muted">{{comment.publish_date}}</small>
                        </span>
                            <strong class="text-success">@{{comment.author}}</strong>
                            <p>
                                {{comment.text}}
                             </p>
                            <div><small class="text-muted">akcja:</small></div>
                            <div><font color="green">{{comment.status}}</font></div>
                            <a href="{{ comment.get_absolute_file_url }}"><span class="{{comment.if_comment_have_file_icon}}" rel-data-toggle="tooltip" data-placement="bottom"
        						                title="{{comment.file.name}}"> {{comment.if_there_is_a_file_return_text }}</a>
                            </div>
                    <a type="button" class="btn btn-dark"  href="{% url 'raportowanie:comment_edit' post.id comment.id %}" rel-data-toggle="tooltip" data-placement="bottom"
						title="Edycja"><i class="fas fa-edit"></i></a>
                    <a type="button" class="btn btn-warning"  href="{% url 'raportowanie:comment_history' post.id comment.id %}" rel-data-toggle="tooltip" data-placement="bottom"
						title="Historia"><i class="fas fa-history"></i></a>
                  <form method="post" action="{% url 'raportowanie:comment_delete' post.id  comment.id %}" onsubmit="return confirm('Czy napewno chcesz usunąć ten komentarz? Jest to operacja nieodwracalna!');">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger" rel-data-toggle="tooltip" data-placement="bottom"
						title="Usuń"><i class="fas fa-trash" ></i></button>
                    </form>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}